"""Score every segmentation method on the same held-out cases, same metric.

The held-out set is the 68 labelled PET scans (29 subjects) from the registration
split's validation subjects, recorded by nnunet_prepare_dataset.py in
eval_cases.json. Ground truth is the real labelsTr annotation.

Methods scored:
  autopet      predictions already produced by inference_all.py (all 560 cases;
               only the 68 held-out ones are read here)
  nnunet       nnU-Net's own final-validation predictions, which already cover
               exactly these 68 cases -- no re-inference needed
  registration segmentation head of the registration network, via --registration-dir

Deliberately NOT evaluated against imagesVal: its PET labels were generated by
the autoPET model, which would score ~1.0 against its own output.

    python evaluate_segmentations.py
    python evaluate_segmentations.py --registration-dir /path/to/preds
"""

import argparse
import csv
import json
import os
from typing import Callable, Dict, List, Optional

import nibabel as nib
import numpy as np

from inference_all import dice_score, is_empty_case

DATA_ROOT = "/home/iml/fryderyk.koegl/data/PSMAReg/PSMAReg_dataset"
LABELS_DIR = os.path.join(DATA_ROOT, "labelsTr")
AUTOPET_DIR = os.path.join(DATA_ROOT, "labelsTr_autopet_fold0")

EVAL_CASES_JSON = ("/home/iml/fryderyk.koegl/code/autopet-3-submission/"
                   "nnUNet_raw/Dataset501_PSMALesion/eval_cases.json")
NNUNET_VAL_DIR = ("/home/iml/fryderyk.koegl/data/PSMAReg-nnunet/nnUNet_results/"
                  "Dataset501_PSMALesion/nnUNetTrainer_PGPSplus__nnUNetPlans__3d_fullres/"
                  "fold_0/validation")

OUTPUT_CSV = "/home/iml/fryderyk.koegl/data/PSMAReg-nnunet/evaluation_per_case.csv"
OUTPUT_JSON = "/home/iml/fryderyk.koegl/data/PSMAReg-nnunet/evaluation_summary.json"

CSV_FIELDS = ["method", "subject", "case_id", "source_filename",
              "dice", "gt_voxels", "pred_voxels", "empty_case"]


def load_eval_cases() -> List[Dict[str, str]]:
    with open(EVAL_CASES_JSON) as f:
        data = json.load(f)
    cases = [
        {"case_id": cid, "source_filename": src, "subject": cid.rsplit("_", 1)[0]}
        for cid, src in zip(data["case_ids"], data["source_filenames"])
    ]
    return sorted(cases, key=lambda c: c["case_id"])


def resolver_for(method: str, registration_dir: Optional[str]) -> Callable:
    """Map a case to its prediction file for the given method."""
    if method == "autopet":
        return lambda c: os.path.join(AUTOPET_DIR, c["source_filename"])
    if method == "nnunet":
        return lambda c: os.path.join(NNUNET_VAL_DIR, c["case_id"] + ".nii.gz")
    if method == "registration":
        def resolve(c):
            # Accept either naming convention without forcing one on the caller.
            for name in (c["source_filename"], c["case_id"] + ".nii.gz"):
                path = os.path.join(registration_dir, name)
                if os.path.isfile(path):
                    return path
            return os.path.join(registration_dir, c["source_filename"])
        return resolve
    raise ValueError(method)


def score_method(method: str, cases: List[Dict[str, str]],
                 resolve: Callable) -> List[dict]:
    rows = []
    for case in cases:
        pred_path = resolve(case)
        if not os.path.isfile(pred_path):
            print(f"  [{method}] missing prediction, skipping: {pred_path}")
            continue

        gt = nib.load(os.path.join(LABELS_DIR, case["source_filename"])).get_fdata()
        pred = nib.load(pred_path).get_fdata()
        if gt.shape != pred.shape:
            print(f"  [{method}] shape mismatch {gt.shape} vs {pred.shape}, "
                  f"skipping: {case['case_id']}")
            continue

        gt_voxels = int((gt > 0).sum())
        pred_voxels = int((pred > 0).sum())
        rows.append({
            "method": method,
            "subject": case["subject"],
            "case_id": case["case_id"],
            "source_filename": case["source_filename"],
            "dice": dice_score(gt, pred),
            "gt_voxels": gt_voxels,
            "pred_voxels": pred_voxels,
            "empty_case": is_empty_case(gt_voxels, pred_voxels),
        })
    return rows


def summarise(rows: List[dict]) -> dict:
    """Three means, because they answer different questions.

    mean_all         every scan, empty-vs-empty counted as 1.0 (the convention
                     inference_all.py used for the 560-case autoPET number)
    mean_nonempty    empty-vs-empty scans dropped -- this is what nnU-Net's own
                     summary.json reports, so it is the comparable figure
    mean_per_subject averages within subject first, so a patient with 7
                     timepoints does not outweigh one with 2
    """
    dices = [r["dice"] for r in rows]
    nonempty = [r["dice"] for r in rows if not r["empty_case"]]

    by_subject: Dict[str, List[float]] = {}
    for r in rows:
        if not r["empty_case"]:
            by_subject.setdefault(r["subject"], []).append(r["dice"])
    subject_means = [float(np.mean(v)) for v in by_subject.values()]

    return {
        "n_cases": len(rows),
        "n_empty_cases": sum(1 for r in rows if r["empty_case"]),
        "n_subjects": len({r["subject"] for r in rows}),
        "mean_all": float(np.mean(dices)) if dices else None,
        "mean_nonempty": float(np.mean(nonempty)) if nonempty else None,
        "n_nonempty": len(nonempty),
        "mean_per_subject": float(np.mean(subject_means)) if subject_means else None,
        "n_subjects_nonempty": len(subject_means),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--registration-dir", default=None,
                        help="folder with the registration network's PET lesion "
                             "predictions for the held-out cases")
    parser.add_argument("--output-csv", default=OUTPUT_CSV)
    parser.add_argument("--output-json", default=OUTPUT_JSON)
    args = parser.parse_args()

    cases = load_eval_cases()
    print(f"held-out cases: {len(cases)} scans from "
          f"{len({c['subject'] for c in cases})} subjects\n")

    methods = ["autopet", "nnunet"]
    if args.registration_dir:
        methods.append("registration")

    all_rows: List[dict] = []
    summaries: Dict[str, dict] = {}
    for method in methods:
        print(f"scoring {method} ...")
        rows = score_method(method, cases, resolver_for(method, args.registration_dir))
        all_rows.extend(rows)
        summaries[method] = summarise(rows)

    os.makedirs(os.path.dirname(args.output_csv), exist_ok=True)
    with open(args.output_csv, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        writer.writeheader()
        for r in all_rows:
            writer.writerow({**r, "dice": f"{r['dice']:.6f}"})
    with open(args.output_json, "w") as f:
        json.dump(summaries, f, indent=2)

    header = (f"\n{'method':14s} {'n':>4s} {'empty':>6s} {'mean_all':>9s} "
              f"{'mean_ne':>9s} {'n_ne':>5s} {'per_subj':>9s}")
    print(header)
    print("-" * len(header))
    for method, s in summaries.items():
        def fmt(x):
            return f"{x:.4f}" if x is not None else "n/a"
        print(f"{method:14s} {s['n_cases']:4d} {s['n_empty_cases']:6d} "
              f"{fmt(s['mean_all']):>9s} {fmt(s['mean_nonempty']):>9s} "
              f"{s['n_nonempty']:5d} {fmt(s['mean_per_subject']):>9s}")
    print(f"\nper-case CSV: {args.output_csv}")
    print(f"summary:      {args.output_json}")
    if not args.registration_dir:
        print("\nregistration network not scored -- pass --registration-dir")


if __name__ == "__main__":
    main()
